- name: get all facts
  hosts:
    - proxmox
    - pi
    - proxmox_all_running
  gather_facts: true
  tasks:
    - setup:
    - ansible.builtin.debug:
        var: hostvars
    - ansible.builtin.debug:
        var: ansible_facts
