- name: install docker
  hosts:
    - proxy
  become: yes
  tasks:
    - name: install pkgs
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true
    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: install docker pkgs
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: add ansible user to docker group
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes
